Sprint 1
ClevertecFrontendLab/AlexKravchenko1605 pull request #1
Opened 2024-02-11 16:37 UTC by AlexKravchenko1605

1.Implemented the first page of the application
2.Made an adaptation according to the layout
3.Done/Deadline  - 11/0/2024 /12.02.2024
4.Used the library 4x.ant.design

2024-02-11 17:12 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 3.
Количество непройденных тестов: 0.
***
**1440-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707671533/1440-1.png)
***
**1440-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707671533/1440-2.png)
***
**1440-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707671533/1440-3.png)
***
**360-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707671533/360-1.png)
***
**360-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707671533/360-2.png)
***
**360-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707671533/360-3.png)
***
**834-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707671533/834-1.png)
***
**834-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707671533/834-2.png)
***
**834-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707671533/834-3.png)

2024-02-11 19:14 UTC, SergeyGlazun requested changes
![image](https://github.com/ClevertecFrontendLab/AlexKravchenko1605/assets/70904466/09f9d9f5-043c-462e-be48-f1a34c39a896)
отступы

2024-02-11 19:18 UTC, SergeyGlazun commented
![image](https://github.com/ClevertecFrontendLab/AlexKravchenko1605/assets/70904466/590ef6c4-068d-4a95-b2d4-41d6f3f6d143)
проверь шрифт и цвет вроде как, посмотри как в макете, если будет правильный шрифт размер и размер блока, должно нормально перенестись

2024-02-11 19:19 UTC, SergeyGlazun commented
![image](https://github.com/ClevertecFrontendLab/AlexKravchenko1605/assets/70904466/93a52634-a77f-468c-b6ff-ec46c39f4691)
цвет другой

2024-02-11 19:19 UTC, SergeyGlazun commented
![image](https://github.com/ClevertecFrontendLab/AlexKravchenko1605/assets/70904466/6843835c-9c2f-4d37-bcae-efe1ab731b2c)
тут тоже цвет и шрифты сверь

2024-02-11 19:20 UTC, SergeyGlazun commented
![image](https://github.com/ClevertecFrontendLab/AlexKravchenko1605/assets/70904466/0bb29bff-5a97-484f-8182-0f09e2cad11c)
тут тоже сверь с макетом

2024-02-12 05:02 UTC, Ivan6813 approved these changes

2024-02-12 18:46 UTC, SergeyGlazun requested changes
!important; плохая практика

2024-02-12 18:46 UTC, SergeyGlazun commented on src/pages/main-page/main-page.css
> +        padding: 0 8px !important;
important плохая практика

2024-02-12 18:46 UTC, SergeyGlazun commented on src/pages/main-page/main-page.tsx
> +                                icon: <CalendarOutlined style={{ color: '#061178' }} />,
попробуйте через css

2024-02-12 18:46 UTC, SergeyGlazun commented on src/layout/AppMainContent/AppMainContent.css
> +    p {
лучше через класс

2024-02-12 18:46 UTC, SergeyGlazun commented on src/layout/AppMainContent/AppMainContent.tsx
> +                <p>
лучше через список ul>li

2024-02-12 19:14 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 3.
Количество непройденных тестов: 0.
***
**1440-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707765286/1440-1.png)
***
**1440-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707765286/1440-2.png)
***
**1440-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707765286/1440-3.png)
***
**360-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707765286/360-1.png)
***
**360-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707765286/360-2.png)
***
**360-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707765286/360-3.png)
***
**834-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707765286/834-1.png)
***
**834-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707765286/834-2.png)
***
**834-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707765286/834-3.png)

2024-02-13 07:00 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 3.
Количество непройденных тестов: 0.
***
**1440-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707807630/1440-1.png)
***
**1440-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707807630/1440-2.png)
***
**1440-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707807630/1440-3.png)
***
**360-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707807630/360-1.png)
***
**360-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707807630/360-2.png)
***
**360-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707807630/360-3.png)
***
**834-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707807630/834-1.png)
***
**834-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707807630/834-2.png)
***
**834-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/AlexKravchenko1605/1707807630/834-3.png)

2024-02-13 07:07 UTC, SergeyGlazun requested changes
![image](https://github.com/ClevertecFrontendLab/AlexKravchenko1605/assets/70904466/3d1ad105-f43d-48a0-8fe5-c07a29e425ee)
погугли как убрать точки в списке

2024-02-13 07:08 UTC, SergeyGlazun commented
![image](https://github.com/ClevertecFrontendLab/AlexKravchenko1605/assets/70904466/4f434214-e26e-4d9b-9787-f4fe490be51d)
отступы еще актуально

2024-02-13 07:09 UTC, SergeyGlazun commented
![image](https://github.com/ClevertecFrontendLab/AlexKravchenko1605/assets/70904466/16389977-3ad0-4b65-acbd-094472c98f6b)
на макете при открытой менюшки текст должен перестроиться

2024-02-13 08:02 UTC, SergeyGlazun approved these changes

2024-02-13 10:09 UTC, merged